// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5q-szijmeroX7L73wXqc-fLkUPeHYWnY',
    appId: '1:546989345403:web:804f4443c83703e987b0de',
    messagingSenderId: '546989345403',
    projectId: 'crudfirebase-9d482',
    authDomain: 'crudfirebase-9d482.firebaseapp.com',
    storageBucket: 'crudfirebase-9d482.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgiWTz26k_BPpUSfl93iPkEbzZMyWgUo',
    appId: '1:546989345403:android:c19e53646f5c4fe587b0de',
    messagingSenderId: '546989345403',
    projectId: 'crudfirebase-9d482',
    storageBucket: 'crudfirebase-9d482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JniE7AQjvvVNu4luyBnItLUWBsDDj5A',
    appId: '1:546989345403:ios:38201f8259bc319587b0de',
    messagingSenderId: '546989345403',
    projectId: 'crudfirebase-9d482',
    storageBucket: 'crudfirebase-9d482.appspot.com',
    iosClientId: '546989345403-2j8nffqgrqqrmttl12l79qs529lrok6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );
}
